import React from 'react'
import { useRef, useEffect, useState } from 'react'   
import videoBG from '../assets/finalvideo.mp4'
import daLogo from "../assets/DA_Logo.png"
import bpLogo from '../assets/Bagong Pilipinas Logo.png'
import { Link } from 'react-router-dom'
import { FaChartLine, FaDollarSign, FaClipboardCheck, FaAddressBook, FaFlask, FaChartBar, FaCalculator, FaCreditCard, FaHome } from 'react-icons/fa';
import { IoMdMenu } from 'react-icons/io';

const sidebarStyles = { 
  toggleBtn: {
    position: 'fixed',
    top: '10px',
    left: '10px',
    background: 'linear-gradient(135deg, #f0f4ff 0%, #f5f9ff 100%)',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    zIndex: 1001,
    padding: '5px',
    borderRadius: '5px',
  },
};

const Sidebar = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };

  const menuItems = [
    { title: 'Home', icon: <FaHome />, link: '/' },
    { title: 'Production Supply and Demand', icon: <FaChartLine />, link: '/ProductionSupplyandDemand' },
    { title: 'Price and Price Trends', icon: <FaDollarSign />, link: '/PriceandPriceTrends' },
    { title: 'Product Standards & Consumer Safety', icon: <FaClipboardCheck />, link: '/ProductStandards' },
    { title: 'Directory & Profiles', icon: <FaAddressBook />, link: '/Directory' },
    { title: 'Res.Info & Tech. Generated by R&D', icon: <FaFlask />, link: '/Research' },
    { title: 'Marketing Data & Forecast', icon: <FaChartBar />, link: '/Marketing' },
    { title: 'Resource Accounting Data', icon: <FaCalculator />, link: '/Resource' },
    { title: 'Credit Facilities & Programs', icon: <FaCreditCard />, link: '/Credit' },
  ];

  return (
    <div className={`sidebar ${isOpen ? 'open' : ''}`}>
      <button style={sidebarStyles.toggleBtn} onClick={toggleSidebar}>
        <IoMdMenu />
      </button>
      <nav>
        <ul>
          {menuItems.map((item, index) => (
            <li key={index}>
              <Link to={item.link}>
                {item.icon}
                <span>{item.title}</span>
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </div>
  );
};

const Main = () => {
  const videoRef = useRef(null);

  useEffect(() => {
    const handleVideoStart = () => {
      if (videoRef.current) {
        videoRef.current.currentTime = 2;
      }
    };

    const videoElement = videoRef.current;
    if (videoElement) {
      videoElement.addEventListener('loadeddata', handleVideoStart);
    }

    return () => {
      if (videoElement) {
        videoElement.removeEventListener('loadeddata', handleVideoStart);
      }
    };
  }, []);

  return (
    <div className='main'>
      <Sidebar />
      <video ref={videoRef} src={videoBG} autoPlay loop muted />
      <div className='dark-overlay'></div>
      <div className='content'>
        <div className='tataks'>
          <img src={daLogo} alt="D.A Logo" className='tatak' />
          <img src={bpLogo} alt="Bagong Pilipinas Logo" className='tatak' />
        </div>
        <h1>Department of Agriculture</h1>
        <p>Regional Field Office 02</p>
        <h2>Regional Information Network Portal</h2>
      </div>
    </div>
  );
};

export default Main;