// Main.jsx
import React, { useRef, useEffect, useState, useCallback } from 'react';
import videoBG from '../assets/finalvideo.mp4';
import daLogo from "../assets/DA_Logo.png";
import bpLogo from '../assets/Bagong Pilipinas Logo.png';
import { Link } from 'react-router-dom';
import { FaChartLine, FaDollarSign, FaClipboardCheck, FaAddressBook, FaFlask, FaChartBar, FaCalculator, FaCreditCard, FaHome } from 'react-icons/fa';
import { IoMdMenu, IoMdClose } from 'react-icons/io';
import '../components/Main.css';

const Sidebar = () => {
  const [isOpen, setIsOpen] = useState(false);

  const menuItems = [
    { title: 'Home', icon: <FaHome />, link: '/' },
    { title: 'Production Supply and Demand', icon: <FaChartLine />, link: '/ProductionSupplyandDemand' },
    { title: 'Price and Price Trends', icon: <FaDollarSign />, link: '/PriceandPriceTrends' },
    { title: 'Product Standards & Consumer Safety', icon: <FaClipboardCheck />, link: '/ProductStandards' },
    { title: 'Directory & Profiles', icon: <FaAddressBook />, link: '/Directory' },
    { title: 'Res.Info & Tech. Generated by R&D', icon: <FaFlask />, link: '/Research' },
    { title: 'Marketing Data & Forecast', icon: <FaChartBar />, link: '/Marketing' },
    { title: 'Resource Accounting Data', icon: <FaCalculator />, link: '/Resource' },
    { title: 'Credit Facilities & Programs', icon: <FaCreditCard />, link: '/Credit' },
  ];

  const toggleSidebar = useCallback(() => {
    setIsOpen(prevState => !prevState);
    document.body.classList.toggle('sidebar-open');
  }, []);

  const handleNavigation = () => {
    setIsOpen(false);
    document.body.classList.remove('sidebar-open');
  };

  useEffect(() => {
    const handleEscape = (e) => {
      if (e.key === 'Escape' && isOpen) {
        toggleSidebar();
      }
    };

    window.addEventListener('keydown', handleEscape);
    return () => window.removeEventListener('keydown', handleEscape);
  }, [isOpen, toggleSidebar]);

  return (
    <>
      <button 
        className="menu-toggle-btn"
        onClick={toggleSidebar}
        aria-label={isOpen ? 'Close menu' : 'Open menu'}
      >
        {isOpen ? <IoMdClose size={24} /> : <IoMdMenu size={24} />}
      </button>

      <div 
        className={`sidebar-overlay ${isOpen ? 'show' : ''}`}
        onClick={toggleSidebar}
        role="presentation"
      />
      
      <div className={`sidebar ${isOpen ? 'open' : ''}`}>
        <nav>
          <ul>
            {menuItems.map((item, index) => (
              <li key={index}>
                <Link 
                  to={item.link}
                  onClick={handleNavigation}
                >
                  {item.icon}
                  <span>{item.title}</span>
                </Link>
              </li>
            ))}
          </ul>
        </nav>
      </div>
    </>
  );
};

const Main = () => {
  const videoRef = useRef(null);

  useEffect(() => {
    const handleVideoStart = () => {
      if (videoRef.current) {
        videoRef.current.currentTime = 2;
      }
    };

    const videoElement = videoRef.current;
    if (videoElement) {
      videoElement.addEventListener('loadeddata', handleVideoStart);
    }

    return () => {
      if (videoElement) {
        videoElement.removeEventListener('loadeddata', handleVideoStart);
      }
    };
  }, []);

  return (
    <div className='main'>
      <Sidebar />
      <video ref={videoRef} src={videoBG} autoPlay loop muted className='background-video' />
      <div className='dark-overlay'></div>
      <div className='content'>
        <div className='tataks'>
          <img src={daLogo} alt="D.A Logo" className='tatak' />
          <img src={bpLogo} alt="Bagong Pilipinas Logo" className='tatak' />
        </div>
        <h1>Department of Agriculture</h1>
        <p>Regional Field Office 02</p>
        <h2>Regional Information Network Portal</h2>
      </div>
    </div>
  );
};

export default Main;