import React, { useState } from "react";
import styled, { keyframes } from "styled-components";
import { Link } from 'react-router-dom';
import { FaChartLine, FaDollarSign, FaClipboardCheck, FaAddressBook, FaFlask, FaChartBar, FaCalculator, FaCreditCard, FaHome } from 'react-icons/fa';
import { IoMdMenu } from 'react-icons/io';
import "../../styles/page.css";
import Footer from '../Footer'
import Animal from '../../assets/animal.PNG'
import Feeds from '../../assets/feeds.PNG'
import F2C2 from '../../assets/f2c2.PNG'
import rsbsa from '../../assets/rsbsa.png'

const fadeIn = keyframes`
  from { opacity: 0; }
  to { opacity: 1; }
`;

const slideUp = keyframes`
  from { transform: translateY(20px); opacity: 0; }
  to { transform: translateY(0); opacity: 1; }
`;

const PageWrapper = styled.div`
  display: flex;
  min-height: 100vh;
  animation: ${fadeIn} 0.5s ease-out;
`;

const MainContent = styled.main`
  flex: 1;
  background-color: #f8f9fa;
  transition: margin-left 0.3s ease-in-out;
  margin-left: ${props => props.isShifted ? '250px' : '0'};

  @media (max-width: 768px) {
    margin-left: 0;
  }
`;

const CardContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  animation: ${fadeIn} 0.5s ease-out;
  padding: 20px;

  @media (max-width: 969px) {
    justify-content: space-around;
  }
`;

const CardWrapper = styled.div`
  flex: 0 0 calc(33.33% - 20px);
  max-width: calc(33.33% - 20px);
  margin-bottom: 20px;
  animation: ${slideUp} 0.5s ease-out;

  @media (max-width: 969px) {
    flex: 0 0 calc(50% - 20px);
    max-width: calc(50% - 20px);
  }

  @media (max-width: 600px) {
    flex: 0 0 100%;
    max-width: 100%;
  }
`;

const HeroSection = styled.div`
  background-color: #f8f9fa;
  color: #333;
  padding: 60px 20px;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: "Poppins", sans-serif;
  animation: ${fadeIn} 0.5s ease-out;
`;

const HeroContent = styled.div`
  max-width: 800px;
  margin: 0 auto;
  animation: ${slideUp} 0.5s ease-out;
`;

const HeroTitle = styled.h1`
  margin: 0;
  font-size: 50px;
  font-weight: 700;
  color: #0072ff;
  text-transform: none;
  letter-spacing: 1px;
  background: linear-gradient(180deg, #0072ff, #00c6ff);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  position: relative;
  display: inline-block;
  animation: ${slideUp} 0.5s ease-out;
`;

const Sidebar = ({ isOpen }) => {
  const menuItems = [
    { title: 'Home', icon: <FaHome />, link: '/' },
    { title: 'Production Supply and Demand', icon: <FaChartLine />, link: '/ProductionSupplyandDemand' },
    { title: 'Price and Price Trends', icon: <FaDollarSign />, link: '/PriceandPriceTrends' },
    { title: 'Product Standards & Consumer Safety', icon: <FaClipboardCheck />, link: '/ProductStandards' },
    { title: 'Directory & Profiles', icon: <FaAddressBook />, link: '/Directory' },
    { title: 'Res.Info & Tech. Generated by R&D', icon: <FaFlask />, link: '/Research' },
    { title: 'Marketing Data & Forecast', icon: <FaChartBar />, link: '/Marketing' },
    { title: 'Resource Accounting Data', icon: <FaCalculator />, link: '/Resource' },
    { title: 'Credit Facilities & Programs', icon: <FaCreditCard />, link: '/Credit' },
  ];

  return (
    <div className={`sidebar ${isOpen ? 'open' : ''}`}>
      <nav>
        <ul>
          {menuItems.map((item, index) => (
            <li key={index}>
              <Link to={item.link}>
                {item.icon}
                <span>{item.title}</span>
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </div>
  );
};

const Hero = () => {
  return (
    <HeroSection>
      <HeroContent>
        <HeroTitle>Directory and Profiles</HeroTitle>
      </HeroContent>
    </HeroSection>
  );
};

function Page() {
  const [isOpen, setIsOpen] = useState(false);
  const [cards] = useState([
    {
      title: "Status of F2C2 Clusters in Region 02",
      text: "Prepared by Field Operations Division",
      imageSrc: F2C2,
      powerBIUrl:
        "https://app.powerbi.com/reportEmbed?reportId=8dc31c46-62b8-4c4d-aa57-45e5a033c2f6&autoAuth=true&ctid=6898061d-1a6b-4e39-adfc-dc8afe072201",
    },
    {
        title: "Registered Animal Facilities in Region 02",
        text: "Prepared by Regulatory Division",
        imageSrc: Animal,
        powerBIUrl:
          "https://app.powerbi.com/view?r=eyJrIjoiNjVmMmMzOTgtNWIyMy00MGFlLWJlNTktZGJhMjliM2E4MjU0IiwidCI6IjY4OTgwNjFkLTFhNmItNGUzOS1hZGZjLWRjOGFmZTA3MjIwMSIsImMiOjEwfQ%3D%3D",
      },
      {
        title: "Feed Establishments in Region 02",
        text: "Prepared by Regulatory Division",
        imageSrc: Feeds,
        powerBIUrl:
          "https://app.powerbi.com/view?r=eyJrIjoiOGU0MTlkYzMtOGM4NC00ZTQ5LWIxMjUtYzYyMjFlMjEyYjc3IiwidCI6IjY4OTgwNjFkLTFhNmItNGUzOS1hZGZjLWRjOGFmZTA3MjIwMSIsImMiOjEwfQ%3D%3D",
      },
      {
        title: "DA-RSBSA (Registry System for Basic Sectors in Agriculture) Demographic",
        text: "Prepared by RSBSA NPMO",
        imageSrc: rsbsa,
        powerBIUrl:
          "https://app.powerbi.com/singleSignOn?ctid=25363027-5264-4a52-82dc-83acbe30cc8b&experience=power-bi&fbclid=IwY2xjawEX2qJleHRuA2FlbQIxMAABHQCa35t7jkr6r2qfMgdrsBaE6_pufbsM_wWB8JVw0pKLIoVSB0W3rrJ4qA_aem_8WrSq_kL8KlBhPgAFhICgg&ru=https%3A%2F%2Fapp.powerbi.com%2Fgroups%2Fme%2Fapps%2Fe7536ff0-3773-4efb-970f-32651c96ec28%2Freports%2Fcce9bd2c-46ac-48d5-91c2-d2ffcac6cdb9%2FReportSection493e614530181d8dc02c%3Fctid%3D25363027-5264-4a52-82dc-83acbe30cc8b%26experience%3Dpower-bi%26fbclid%3DIwY2xjawEX2qJleHRuA2FlbQIxMAABHQCa35t7jkr6r2qfMgdrsBaE6_pufbsM_wWB8JVw0pKLIoVSB0W3rrJ4qA_aem_8WrSq_kL8KlBhPgAFhICgg%26noSignUpCheck%3D1",
      },
  ]);

  const handleViewAnalytics = (url) => {
    if (url) {
      window.open(url, "_blank", "noopener,noreferrer");
    }
  };

  return (
    <PageWrapper>
      <button className="toggle-btn" onClick={() => setIsOpen(!isOpen)}>
        <IoMdMenu />
      </button>
      <Sidebar isOpen={isOpen} />
      <MainContent isShifted={isOpen}>
        <Hero />
        <div className="container">
          <CardContainer>
            {cards.map((card, i) => (
              <CardWrapper key={i}>
                <div className="card">
                  <h3>{card.title}</h3>
                  <div className="image-container">
                    <img 
                      src={card.imageSrc} 
                      alt={card.title}
                      style={{
                        maxWidth: "100%",
                        height: "auto",
                        display: "block",
                        margin: "0 auto",
                      }}
                    />
                  </div>
                  <p>{card.text}</p>
                  {card.powerBIUrl && (
                    <button
                      onClick={() => handleViewAnalytics(card.powerBIUrl)}
                      className="btn"
                    >
                      View Analytics
                    </button>
                  )}
                </div>
              </CardWrapper>
            ))}
          </CardContainer>
        </div>
        <Footer />
      </MainContent>
    </PageWrapper>
  );
}

export default Page;