import React, { useState } from "react";
import Lottie from "react-lottie";
import styled, { keyframes } from "styled-components";
import { Link } from 'react-router-dom';
import { FaChartLine, FaDollarSign, FaClipboardCheck, FaAddressBook, FaFlask, FaChartBar, FaCalculator, FaCreditCard, FaHome } from 'react-icons/fa';
import { IoMdMenu } from 'react-icons/io';
// import pmedAnimation from "../../animations/pmed2.json";
import "../../styles/page.css";
import Footer from '../Footer'

const fadeIn = keyframes`
  from { opacity: 0; }
  to { opacity: 1; }
`;

const slideUp = keyframes`
  from { transform: translateY(20px); opacity: 0; }
  to { transform: translateY(0); opacity: 1; }
`;

const PageWrapper = styled.div`
  display: flex;
  min-height: 100vh;
  flex-direction: column;
  animation: ${fadeIn} 0.5s ease-out;
`;

const MainContent = styled.main`
  flex: 1 0 auto;
  display: flex;
  flex-direction: column;
  background-color: #f8f9fa;
  transition: margin-left 0.3s ease-in-out;
  margin-left: ${props => props.isShifted ? '250px' : '0'};

  @media (max-width: 768px) {
    margin-left: 0;
  }
`;


const CardContainer = styled.div`
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  animation: ${fadeIn} 0.5s ease-out;
  padding: 20px;

  @media (max-width: 969px) {
    justify-content: space-around;
  }
`;

const CardWrapper = styled.div`
  flex: 0 0 calc(33.33% - 20px);
  max-width: calc(33.33% - 20px);
  margin-bottom: 20px;
  animation: ${slideUp} 0.5s ease-out;

  @media (max-width: 969px) {
    flex: 0 0 calc(50% - 20px);
    max-width: calc(50% - 20px);
  }

  @media (max-width: 600px) {
    flex: 0 0 100%;
    max-width: 100%;
  }
`;

const HeroSection = styled.div`
  background-color: #f8f9fa;
  color: #333;
  padding: 60px 20px;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: center;
  font-family: "Poppins", sans-serif;
  animation: ${fadeIn} 0.5s ease-out;
`;

const HeroContent = styled.div`
  max-width: 800px;
  margin: 0 auto;
  animation: ${slideUp} 0.5s ease-out;
`;

const HeroTitle = styled.h1`
  margin: 0;
  font-size: 50px;
  font-weight: 700;
  color: #0072ff;
  text-transform: none;
  letter-spacing: 1px;
  background: linear-gradient(180deg, #0072ff, #00c6ff);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  position: relative;
  display: inline-block;
  animation: ${slideUp} 0.5s ease-out;
`;

const Sidebar = ({ isOpen }) => {
  const menuItems = [
    { title: 'Home', icon: <FaHome />, link: '/' },
    { title: 'Production Supply and Demand', icon: <FaChartLine />, link: '/ProductionSupplyandDemand' },
    { title: 'Price and Price Trends', icon: <FaDollarSign />, link: '/PriceandPriceTrends' },
    { title: 'Product Standards & Consumer Safety', icon: <FaClipboardCheck />, link: '/ProductStandards' },
    { title: 'Directory & Profiles', icon: <FaAddressBook />, link: '/Directory' },
    { title: 'Res.Info & Tech. Generated by R&D', icon: <FaFlask />, link: '/Research' },
    { title: 'Marketing Data & Forecast', icon: <FaChartBar />, link: '/Marketing' },
    { title: 'Resource Accounting Data', icon: <FaCalculator />, link: '/Resource' },
    { title: 'Credit Facilities & Programs', icon: <FaCreditCard />, link: '/Credit' },
  ];

  return (
    <div className={`sidebar ${isOpen ? 'open' : ''}`}>
      <nav>
        <ul>
          {menuItems.map((item, index) => (
            <li key={index}>
              <Link to={item.link}>
                {item.icon}
                <span>{item.title}</span>
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </div>
  );
};

const Hero = () => {
  return (
    <HeroSection>
      <HeroContent>
        <HeroTitle>Marketing Data and Forecasts</HeroTitle>
      </HeroContent>
    </HeroSection>
  );
};

function Page() {
  const [isOpen, setIsOpen] = useState(false);
  const [cards] = useState([
    // {
    //   title: "",
    //   text: "",
    //   animationOptions: {
    //     loop: true,
    //     autoplay: true,
    //     animationData: pmedAnimation,
    //     rendererSettings: {
    //       preserveAspectRatio: "xMidYMid slice",
    //     },
    //   },
    //   powerBIUrl:
    //     "",
    // },
  ]);

  const handleViewAnalytics = (url) => {
    if (url) {
      window.open(url, "_blank", "noopener,noreferrer");
    }
  };

  return (
    <PageWrapper>
      <button className="toggle-btn" onClick={() => setIsOpen(!isOpen)}>
        <IoMdMenu />
      </button>
      <Sidebar isOpen={isOpen} />
      <MainContent isShifted={isOpen}>
      <div style={{ flex: '1 0 auto' }}>
        <Hero />
        <div className="container">
          <CardContainer>
            {cards.map((card, i) => (
              <CardWrapper key={i}>
                <div className="card">
                  <h3>{card.title}</h3>
                  <div className="lottie-container">
                    {card.animationOptions && (
                      <Lottie
                        options={card.animationOptions}
                        height="100%"
                        width="100%"
                        style={{
                          maxWidth: "225px",
                          maxHeight: "225px",
                          margin: "0 auto",
                        }}
                      />
                    )}
                  </div>
                  <p>{card.text}</p>
                  {card.powerBIUrl && (
                    <button
                      onClick={() => handleViewAnalytics(card.powerBIUrl)}
                      className="btn"
                    >
                      View Analytics
                    </button>
                  )}
                </div>
              </CardWrapper>
            ))}
          </CardContainer>
        </div>
        </div>
        <Footer/>
      </MainContent>
    </PageWrapper>
  );
}

export default Page;